apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  serviceAccountName: test
  containers:
  - image: amazon/aws-cli
    name: test
    command: ['aws' , 's3' , 'ls' ]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
