apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: power-user-dev-role
  namespace: dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - serviceaccounts
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - list
  - get
  - watch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - get
  - watch
  - create
  - delete
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: power-user-dev-role-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: power-user-dev-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: power-user